name: Deploy MkDocs Site

on:
  push:
    branches:
      - main # Or your main branch name, e.g., master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Or specify a specific version

      - name: Install MkDocs and Plugins
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin

      - name: Build MkDocs Site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site # Folder where MkDocs builds the HTML
          force_orphan: true  # If gh-pages branch doesn't exist yet
          publish_branch: gh-pages # Output branch name